config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'pages#index'

  get '*pages/edit', to: 'pages#edit', as: 'edit_page'
  get '(*pages)/add', to: 'pages#new', as: 'new_page'
  get '*pages', to: 'pages#show', as: 'page'
  patch '*pages', to: 'pages#update', as: 'update_page'
  post '(*pages)', to: 'pages#create', as: 'create_page'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :parent_page, class_name: 'Page', foreign_key: 'parent_page_id', optional: true
  has_many :child_pages, class_name: 'Page', foreign_key: 'parent_page_id', dependent: :nullify

  # making replasements to produce content for show and leave content_raw for edit
  before_save :construct_content

  validates_format_of :name, with: /\A[a-zA-Z0-9_А-Яа-я]+\z/, message: 'must contain only: _ A-z А-я 0-9'
  # I duplicate this in database migration in case of we have multiple sources of pages
  validates_uniqueness_of :name, message: 'must be unique'
  validates :name, exclusion: { in: %w[edit add], message: 'must NOT be edit or add' }

  scope :root, -> { where(parent_page_id: nil) }

  # Returns relative path to page according to our routing system
  def path
    Page.join_recursive do |query|
      query
        .start_with(id: id) { select('0 depth') }
        .select(query.prior[:depth] - 1, start_with: false)
        .connect_by(parent_page_id: :id)
    end.order('depth ASC').pluck(:name).join('/')
  end

  # Returns hierarchy tree for rendering
  def hierarchy
    # get whole hierarchy and group for future use
    pages = Page.join_recursive do |query|
      query.start_with(parent_page_id: id)
           .connect_by(id: :parent_page_id)
    end.group_by(&:parent_page_id)

    { name: name, path: path, pages: pages[id] ? hasify_children(pages, id, "#{path}/") : [] }
  end

  protected

  def hasify_children(pages, parent_id, parent_path)
    pages[parent_id].map do |page|
      { name: page.name, path: "#{parent_path}#{page.name}",
        pages: pages[page.id] ? hasify_children(pages, page.id, "#{parent_path}#{page.name}/") : [] }
    end
  end

  private

  # making replasements to produce content for show and leave content_raw for edit
  def construct_content
    # replace *[content]* with <b>content</b>
    constructed_content = content_raw.gsub(/(\*\[)(.+)(\]\*)/, '<b>\2</b>')
    # replace //content// with <i>content</i>
    constructed_content = constructed_content.gsub(/(\\\\)(.+)(\\\\)/, '<i>\2</i>')
    # replace ((path/to/something content)) with <a href="/path/to/something">content</a>
    self.content = constructed_content.gsub(%r{(\(\()(.+/.+)( )(.+)(\)\))},
                                            '<a href="/\2">\4</a>')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :find_page, only: %i[show edit update]
  before_action :validate_route, only: %i[show edit update]

  def index
    @page_hierarchies = Page.root.map(&:hierarchy)
  end

  def show
    @hierarchy = @page.hierarchy
  end

  def edit; end

  def update
    if @page.update(page_params)
      redirect_to page_path(@page.path)
    else
      render :edit
    end
  end

  def new
    @page = Page.new
  end

  def create
    if params[:pages]
      parent_page = find_page
      validate_route
    end
    @page = Page.new(page_params.merge(parent_page_id: parent_page&.id))

    if @page.save
      redirect_to page_path(@page.path)
    else
      render :new
    end
  end

  private

  def page_params
    params.require(:page).permit(:name, :content_raw, :header)
  end

  def find_page
    return unless params[:pages]

    @page = Page.find_by(name: params[:pages].split('/').last)
    @page || (raise ActionController::RoutingError, 'Not Found')
  rescue StandardError
    render file: "#{Rails.root}/public/404", status: :not_found
  end

  def validate_route
    # I decided to check if the client knew the exact page hierarchy to access it.
    raise ActionController::RoutingError, 'Not Found' unless @page&.path == params[:pages]
  rescue StandardError
    render file: "#{Rails.root}/public/404", status: :not_found
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pulstest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/_page_hierarchy.html.slim
ul
  li = link_to hierarchy[:name], page_path(hierarchy[:path])
  - hierarchy[:pages].each do |page_hierarchy|
    = render partial: 'page_hierarchy', locals: { hierarchy: page_hierarchy }

app/views/pages/edit.html.slim
= render 'form'

app/views/pages/index.html.slim
- @page_hierarchies.each do |hierarchy|
  = render partial: 'page_hierarchy', locals: { hierarchy: hierarchy }

app/views/pages/new.html.slim
= form_for @page, url: create_page_path(params[:pages]) do |form|
  p
    = form.label :name
    = form.text_field :name
  
  p
    = form.label :header
    = form.text_field :header

  p
    = form.label :content_raw, 'Content'
    = form.text_area :content_raw, rows: 7, cols: 60

  p = form.submit class: 'btn btn-primary'

app/views/pages/show.html.slim
h1 = @page.header
= render partial: 'page_hierarchy', locals: { hierarchy: @hierarchy }
- if @page.content
  .content = @page.content.html_safe